# Generated by Django 5.1.15 on 2026-08-13 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_vendedor', models.CharField(default='Casal Vendedor', max_length=150, verbose_name='Nome do Vendedor / Casal')),
                ('whatsapp', models.CharField(blank=True, help_text='Apenas números com DDI e DDD (ex: 5511999999999)', max_length=30, verbose_name='WhatsApp')),
                ('telegram', models.CharField(blank=True, help_text='Nome de usuário ou link (ex: @usuario ou t.me/usuario)', max_length=100, verbose_name='Telegram')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail de Contato')),
                ('chave_pix', models.CharField(blank=True, help_text='Chave PIX para pagamentos diretos', max_length=255, verbose_name='Chave PIX')),
                ('mensagem_boas_vindas', models.TextField(blank=True, default='Olá! Seja bem-vindo à nossa página de desapegos. Todos os itens foram bem cuidados.', verbose_name='Mensagem de Boas-Vindas')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do Vendedor',
                'verbose_name_plural': 'Configurações do Vendedor',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Item')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug (URL amigável)')),
                ('descricao_ia', models.TextField(blank=True, help_text='Descrição gerada automaticamente pela pipeline de IA', verbose_name='Descrição Sugerida por IA')),
                ('descricao_manual', models.TextField(blank=True, help_text='Texto personalizado ou revisado que será exibido aos compradores', verbose_name='Descrição Final / Observações do Vendedor')),
                ('preco_novo_referencia', models.DecimalField(blank=True, decimal_places=2, help_text='Preço de mercado do produto novo para comparação', max_digits=10, null=True, verbose_name='Preço Novo de Referência (R$)')),
                ('preco_usado', models.DecimalField(blank=True, decimal_places=2, help_text='Preço pedido para venda do item usado', max_digits=10, null=True, verbose_name='Preço de Venda (R$)')),
                ('preco_aluguel', models.DecimalField(blank=True, decimal_places=2, help_text='Valor sugerido caso seja disponibilizado para aluguel', max_digits=10, null=True, verbose_name='Preço de Aluguel (R$)')),
                ('tipo_anuncio', models.CharField(choices=[('venda', 'Venda'), ('aluguel', 'Aluguel'), ('ambos', 'Venda e Aluguel')], default='venda', max_length=20, verbose_name='Tipo de Anúncio')),
                ('estado_conservacao', models.CharField(choices=[('novo', 'Novo / Lacrado'), ('excelente', 'Excelente estado (pouco uso)'), ('bom', 'Bom estado (marcas leves de uso)'), ('marcas_uso', 'Marcas de uso visíveis'), ('defeito_reparo', 'Com avarias / Para reparo')], default='bom', max_length=30, verbose_name='Estado de Conservação')),
                ('categoria', models.CharField(choices=[('eletronicos', 'Eletrônicos e Informática'), ('moveis', 'Móveis e Decoração'), ('eletrodomesticos', 'Eletrodomésticos'), ('ferramentas', 'Ferramentas e Casa'), ('instrumentos', 'Instrumentos Musicais'), ('vestuario', 'Roupas e Acessórios'), ('esportes', 'Esportes e Lazer'), ('livros', 'Livros e Colecionáveis'), ('outros', 'Outros')], default='outros', max_length=50, verbose_name='Categoria')),
                ('defeitos_visiveis', models.TextField(blank=True, help_text='Defeitos identificados pela visão computacional ou anotados manualmente', verbose_name='Defeitos ou Marcas Visíveis')),
                ('urls_referencia', models.JSONField(blank=True, default=list, help_text='Links de pesquisas de preço (Amazon, Mercado Livre, OLX, etc.)', verbose_name='URLs de Referência de Mercado')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('aprovado', 'Aprovado'), ('vendido', 'Vendido'), ('alugado', 'Alugado')], db_index=True, default='rascunho', max_length=20, verbose_name='Status do Item')),
                ('destaque', models.BooleanField(default=False, verbose_name='Item em Destaque?')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ImagemItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='itens/%Y/%m/', verbose_name='Arquivo de Imagem')),
                ('legenda', models.CharField(blank=True, max_length=200, verbose_name='Legenda / Observação da Foto')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('principal', models.BooleanField(default=False, verbose_name='Imagem Principal')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='core.item', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Imagem do Item',
                'verbose_name_plural': 'Imagens do Item',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
