# Generated by Django 5.1.15 on 2026-08-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaovendedor',
            name='tempo_espera_busca_titulo',
            field=models.DecimalField(decimal_places=1, default=2.0, help_text='Intervalo sem digitação para pesquisar na internet (padrão: 2.0s). Use 0 para desativar a busca automática e permitir apenas busca manual clicando no ícone.', max_digits=3, verbose_name='Tempo de Espera para Busca do Título (segundos)'),
        ),
    ]
