# Generated by Django 5.1.15 on 2026-08-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configuracaovendedor_tempo_espera_busca_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaovendedor',
            name='condicoes_retirada_envio',
            field=models.TextField(blank=True, default='## 🚚 **Condições de Retirada & Envio**\n\n- **Retirada em mãos:** Combinar local e horário com o vendedor. O pagamento pode ser em dinheiro ou Pix.\n- **Envio:** Por Correios (PAC ou SEDEX) mediante pagamento do frete. O produto será embalado com proteção para evitar danos no transporte.\n- **Garantia:** Não há garantia, mas o produto é testado e funcionando. Em caso de defeito no envio, o vendedor se responsabiliza.\n\n---\n\n**Nota:** Este anúncio é transparente quanto ao estado do produto. Qualquer dúvida, entre em contato. O modelo exato pode ser confirmado pelo vendedor se necessário.', help_text='Texto padrão anexado automaticamente ao final das descrições geradas para os anúncios (Markdown suportado).', verbose_name='Condições de Retirada & Envio (Padrão)'),
        ),
    ]
